### ISSUE TITLE
Do not include personal external storages

### ISSUE THREAD

**Issue by PVince81** [owncloud/configreport#104]
Personal external storages mean we iterate over all users and the list can become very long.

We should instead just count how many personal storages there are.

For the system wide mounts we can list them as we don't expect them to be as much as personal mounts.

@cdamken @sharidas showstopper for configreport 0.2.0

**Comment by sharidas** [comment]
Created PR https://github.com/owncloud/configreport/pull/105 against branch `release-0.2.0`
