### ISSUE TITLE
Find a better way to count users / potential timeout

### ISSUE THREAD

**Issue by PVince81** [owncloud/configreport#11]
Seems we're iterating over all users somehow: https://github.com/owncloud/configreport/blob/master/lib/ReportDataCollector.php#L169

In huge setups this is likely to run into timeouts.

Not sure if there is a better way...

@phisch

**Comment by michaelstingl** [comment]
related:
- https://github.com/owncloud/enterprise/issues/1653
- https://github.com/owncloud/enterprise/issues/531

**Comment by tomneedham** [comment]
We should use `userManager->countUsers`

**Comment by butonic** [comment]
fixed with the account table
