### ISSUE TITLE
Item order in report

### ISSUE THREAD

**Issue by mmattel** [owncloud/configreport#13]
If I run the config report, the sort order of the items are:

**Current:**
basic
integrity checker
apps
config
phpinfo

**Proposal:** reorder the items
basic
config
integrity checker
apps
phpinfo

**Benefit:**
basic, integrity checker and config are short
apps and phpinfo are long
things are logically more together
manual looking into makes reading easier

**Comment by phisch** [comment]
Closing because #15 merged!
