### ISSUE TITLE
[QA] phpinfo section is empty

### ISSUE THREAD

**Issue by jnweiger** [owncloud/configreport#168]
Seen with configreport-0.2.1-rc1 (not a regression, also seen with configreport-0.2.0 and core 10.8.0)

 *  Run configreport:generate
 * look for empty sections. `'"phpinfo": []`BAD

Expected behaviour:
 * there is code in the configreport app, that retrieves and postprocesses phpinfo(-1) output.

**Comment by iasdeoupxe** [comment]
Duplicate of #96 and solved by #199?
