### ISSUE TITLE
Unit test failing at nightly

### ISSUE THREAD

**Issue by SagarGi** [owncloud/configreport#184]
### Description
```
There was 1 failure:

1) OCA\ConfigReport\Tests\ReportDataCollectorTest::testGetOCTablesArray
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
         0 => Array (...)
         1 => Array (
             0 => Array (
+                0 => '0'
+                1 => false
+                2 => false
+                3 => 'integer'
+            )
+        )

.....................

/var/www/owncloud/server/apps/configreport/tests/unit/ReportDataCollectorTest.php:657
phpvfscomposer:///var/www/owncloud/server/lib/composer/phpunit/phpunit/phpunit:97
```

Failed Build: https://drone.owncloud.com/owncloud/configreport/2111/5/4 Might nieed some investigation why this is failing.

**Comment by SwikritiT** [comment]
Unit test failing on files primary s3 for same reason https://drone.owncloud.com/owncloud/files_primary_s3/3395/5/8

**Comment by amrita-shrestha** [comment]
new table `creation_time` has been added 
```
"creation_time": {
                            "type": "integer",
                            "null": false,
                            "default": "0",
                            "autoIncrement": false
                        }

```
This changes made unit test to fail

**Comment by phil-davis** [comment]
@pako81 @DeepDiver1975 @jvillafanez is there any real code that should be changed/enhanced here because of the new creation time user account data item added in core https://github.com/owncloud/core/pull/40588 ?

Or is fixing the unit tests (PR #185 ) all that is needed?

**Comment by DeepDiver1975** [comment]
> Or is fixing the unit tests (PR #185 ) all that is needed?

I'd say this is enough. THX
