### ISSUE TITLE
handle licence-key as sensitive in report

### ISSUE THREAD

**Issue by felixboehm** [owncloud/configreport#26]
The licence key should not be exposed, when adding a config-report to a support issue.
@phisch can you remove the key and just provide info about the key: 

- valid until 2017-10-04
- no licence key 

@pmaier1 @hodyroff

**Comment by PVince81** [comment]
I suggest filtering out the license key as most critical item.

Providing the extra info must be done from within the enterprise_key app through plugins. We don't want to expose key related logic in the public configreport code.

**Comment by PVince81** [comment]
@sharidas can you take care of this ?

@phisch please focus on your other more complex tasks, thanks

**Comment by PVince81** [comment]
@sharidas filter out the license key from the output like we do for passwords, I think that should be enough to make this non-critical.

**Comment by PVince81** [comment]
For having the enterprise_key app provide the license details, we first need https://github.com/owncloud/configreport/issues/24 to be added (extension point for apps to provide their own config stuff)

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/enterprise_key/issues/58 for providing key info
