### ISSUE TITLE
As an ownCloud admin I would like to create the configreport with a occ command

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/configreport#3]
Currently, ownCloud only has `occ config:list` to get information about the config on the command line. Creating the full configreport with `occ` would be awesome.

**Comment by PhilippSchaffrath** [comment]
@michaelstingl do you mean like creating a file? Because the command generates the same data like the webinterface.

**Comment by michaelstingl** [comment]
In oC 9.1.3 EE the output from `occ config:list` is different from the `config_report` that can be downloaded on the Admin page.

![config-report-1](https://cloud.githubusercontent.com/assets/214010/21312954/46241254-c5ef-11e6-81ef-0b65966c191c.png)

I'm looking for a way to create the `config_report` in the CLI.

**Comment by PhilippSchaffrath** [comment]
@michaelstingl `configreport:generate` generates the same report as the button on the admin page.

Can you test and evaluate if this is what you need?
