### ISSUE TITLE
[10.0.2] ~~Missing~~ Hard to find button to generate config_report in the web UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/configreport#35]
@phisch Why is there no longer a button to generate the config_report in the admin web UI ?

I have Admin Config Report 0.1.1 installed on my oC 10.0.2 instance.

**Comment by michaelstingl** [comment]
Ups, found it. It's in the "Help & Tips" section:

![cursor_and_settings_-_owncloud_and_labels_ _owncloud_configreport](https://user-images.githubusercontent.com/214010/28470245-72c557d0-6e39-11e7-8d92-6d2d0024c363.png)

@pmaier1 Is "Admin > Help & Tips" section the best, or should it be better moved to the "Admin > General" section, where the "Log" and the "System Status" is too?

**Comment by pmaier1** [comment]
Yes, agree. This was part of my feedback after the settings design rework but it was never implemented.

Should be moved to "Admin > General".

**Comment by pmaier1** [comment]
@tomneedham Can you assign, move to 'development' milestone and change this, please? thanks!

**Comment by michaelstingl** [comment]
@tomneedham @pmaier1 10.0.5 rc3 and still in "Admin > Help & Tips" section?

**Comment by PVince81** [comment]
in 10.0.6 it's in Admin -> General now
