### ISSUE TITLE
Ship it with older releases

### ISSUE THREAD

**Issue by PVince81** [owncloud/configreport#6]
- [x] test if it works with 9.0
- [x] test if it works with 9.1
- [x] ship with 9.0
- [x] ship with 9.1

@PhilippSchaffrath is it ready for testing ? Can you confirm that the code is compatible with older versions ? If not we might need to do backport branches with adjusted code.

**Comment by PhilippSchaffrath** [comment]
I'll test it.

**Comment by PVince81** [comment]
It's merged.

Any update on the backports ?

**Comment by PhilippSchaffrath** [comment]
Works with 9.1, not with 9.0 though, creating branch for 9.0.

**Comment by PVince81** [comment]
Is there a PR for the 9.1 backport ?

Let me know when backports are done so I can update the release scripts to include the app in the next release.

**Comment by PhilippSchaffrath** [comment]
Just managed to get it working with 9.0.

9.1+ works with master, creating identical branches for 9.1, 9.2... seems bad. How do we handle this usually @PVince81?

Branches incomming.

**Comment by PVince81** [comment]
Hmm, indeed. We never had this kind of situation before.

If you tested it with 9.1 then let's just create a stable9.1 and stable9 branches from master then

**Comment by PhilippSchaffrath** [comment]
Branch `stable9` works with 9.0, `stable9.1` works with everything > 9.1. There is a good chance that `stable9` works with older versions too in case we need this.

**Comment by PVince81** [comment]
Any update on the backports ? Else move to 9.1.5

**Comment by PVince81** [comment]
As discussed, I'll update the release scripts.
To be tested in the tarball release.

**Comment by PVince81** [comment]
It's in the tarballs now, closing
