### ISSUE TITLE
travis setup?

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/configreport#8]

**Comment by DeepDiver1975** [comment]
@phisch please take care of this - in case you need help - let me know - THX

**Comment by Prakharsvnit** [comment]
@DeepDiver1975 I'm interested in Travis CI setup,I tried Travis once.link is [here](https://github.com/Prakharsvnit/aaa_fullstack_1511_travis). How can i go ahead in setting up TravisCI for this repo.?

**Comment by phisch** [comment]
@Prakharsvnit sure, go ahead! Let me or @DeepDiver1975 know if you have questions!

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I'm interested in Travis CI setup,I tried Travis once.link is here. How can i go ahead in setting up TravisCI for this repo.?

travis is already enabled on this repo - go ahead by submitting a PR holding the .travis.yml file.

Please have a look at other repos on how we do app testing in travis. THX

**Comment by Prakharsvnit** [comment]
PR here [#16](https://github.com/owncloud/configreport/pull/16) .There are many errors as this is my first time creating .travis.yml file.I'm confused what should be written in script part.Please suggest changes. 
@DeepDiver1975 @phisch

**Comment by DeepDiver1975** [comment]
@patrickjahns we shall add travis/drone in here ...... just saying

**Comment by patrickjahns** [comment]
can do - but it doesn't have any tests -> maybe a junior job for writing some tests for this app?

**Comment by DeepDiver1975** [comment]
> can do - but it doesn't have any tests -> maybe a junior job for writing some tests for this app?

well at least 'test' if the app can be enabled on supported owncloud and php versions and some basic linting. unit tests need to be added for sure .....
