### ISSUE TITLE
Tests are not executed with Oracle ... 

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/configreport#87]
... as a result update testing fails - https://drone.owncloud.com/owncloud/update-testing/296/86

**Comment by PVince81** [comment]
@sharidas @phil-davis is this solved now ? I saw some activity in the config report repo

**Comment by sharidas** [comment]
Now the tests are executed with oracle in master branch reference: https://github.com/owncloud/configreport/pull/91. 
The subsequent stable10 branch PR is https://github.com/owncloud/configreport/pull/86.

**Comment by phil-davis** [comment]
Like @sharidas says, get stable10 PR #86 merged and the Oracle world should be happy again.

**Comment by PVince81** [comment]
ok, merged
