### ISSUE TITLE
CLI configreport does not include phpinfo

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/configreport#96]
When generating a configreport via `occ configreport:generate` there is no information provided about the installed php version and runtime.

However it is useful to also receive information on the CLI runtime, to see whether or not certain php modules are configured also for CLI and if it would differ from the apache configuration

## Expected behavior
`occ configreport:generate` contains a valid phpinfo array

## Actual behavior
`occ configreport:generate` contains a empty array: `"phpinfo": []`

## Steps to reproduce
1) issue `occ configreport:generate` on CLI

**Comment by iasdeoupxe** [comment]
Solved by #199?
